//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class prioridades
    {
        public int pri_codigo { get; set; }
        public string pri_descricao { get; set; }
        public Nullable<int> tar_codigo { get; set; }
    
        public virtual tarefa tarefa { get; set; }
    }
}
