//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarefa()
        {
            this.prioridades = new HashSet<prioridades>();
        }
    
        public int tar_codigo { get; set; }
        public string tar_titulo { get; set; }
        public string tar_descricao { get; set; }
        public Nullable<System.DateTime> tar_dataCriacao { get; set; }
        public Nullable<int> usu_codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prioridades> prioridades { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
